
<!DOCTYPE html> <html lang="vi-VN" dir="ltr" class="aui ltr"> <head> <title>BankFast Login - VietinBank</title> <meta content="width=1366, maximum-scale=1.0, minimal-ui" name="viewport" > <meta content="text/html; charset=UTF-8" http-equiv="content-type" /> <link href="https://ebanking.vietinbank.vn/rcas/portal/vietinbank-theme/images/favicon.ico" rel="Shortcut Icon" /> <link href="https&#x3a;&#x2f;&#x2f;ebanking&#x2e;vietinbank&#x2e;vn&#x2f;rcas&#x2f;portal&#x2f;web&#x2f;retail" rel="canonical" /> <link href="https&#x26;&#x23;x3a&#x3b;&#x26;&#x23;x2f&#x3b;&#x26;&#x23;x2f&#x3b;ebanking&#x26;&#x23;x2e&#x3b;vietinbank&#x26;&#x23;x2e&#x3b;vn&#x26;&#x23;x2f&#x3b;rcas&#x26;&#x23;x2f&#x3b;portal&#x26;&#x23;x2f&#x3b;web&#x26;&#x23;x2f&#x3b;retail&#x2f;en" hreflang="en-US" rel="alternate" /> <link href="https&#x3a;&#x2f;&#x2f;ebanking&#x2e;vietinbank&#x2e;vn&#x2f;rcas&#x2f;portal&#x2f;web&#x2f;retail" hreflang="x-default" rel="alternate" /> <link href="https&#x26;&#x23;x3a&#x3b;&#x26;&#x23;x2f&#x3b;&#x26;&#x23;x2f&#x3b;ebanking&#x26;&#x23;x2e&#x3b;vietinbank&#x26;&#x23;x2e&#x3b;vn&#x26;&#x23;x2f&#x3b;rcas&#x26;&#x23;x2f&#x3b;portal&#x26;&#x23;x2f&#x3b;web&#x26;&#x23;x2f&#x3b;retail&#x2f;vi" hreflang="vi-VN" rel="alternate" /> <link class="lfr-css-file" href="https&#x3a;&#x2f;&#x2f;ebanking&#x2e;vietinbank&#x2e;vn&#x2f;rcas&#x2f;portal&#x2f;vietinbank-theme&#x2f;css&#x2f;aui&#x2e;css&#x3f;browserId&#x3d;other&#x26;themeId&#x3d;vietinbank_WAR_vietinbanktheme&#x26;minifierType&#x3d;css&#x26;languageId&#x3d;vi_VN&#x26;b&#x3d;6201&#x26;t&#x3d;1583748970000" rel="stylesheet" type="text/css" /> <link href="&#x2f;rcas&#x2f;portal&#x2f;html&#x2f;css&#x2f;main&#x2e;css&#x3f;browserId&#x3d;other&#x26;themeId&#x3d;vietinbank_WAR_vietinbanktheme&#x26;minifierType&#x3d;css&#x26;languageId&#x3d;vi_VN&#x26;b&#x3d;6201&#x26;t&#x3d;1583748970000" rel="stylesheet" type="text/css" /> <link href="https://ebanking.vietinbank.vn/rcas/portal/html/portlet/journal_content/css/main.css?browserId=other&amp;themeId=vietinbank_WAR_vietinbanktheme&amp;minifierType=css&amp;languageId=vi_VN&amp;b=6201&amp;t=1584020868000" rel="stylesheet" type="text/css" /> <link href="https://ebanking.vietinbank.vn/rcas/portal/html/portlet/journal/css/main.css?browserId=other&amp;themeId=vietinbank_WAR_vietinbanktheme&amp;minifierType=css&amp;languageId=vi_VN&amp;b=6201&amp;t=1584020868000" rel="stylesheet" type="text/css" /> <link href="https://ebanking.vietinbank.vn/rcas/portal/html/portlet/login/css/main.css?browserId=other&amp;themeId=vietinbank_WAR_vietinbanktheme&amp;minifierType=css&amp;languageId=vi_VN&amp;b=6201&amp;t=1584020868000" rel="stylesheet" type="text/css" /> <script type="text/javascript">var Liferay={Browser:{acceptsGzip:function(){return false},getMajorVersion:function(){return 80},getRevision:function(){return"537.36"},getVersion:function(){return"80.0"},isAir:function(){return false},isChrome:function(){return true},isFirefox:function(){return false},isGecko:function(){return true},isIe:function(){return false},isIphone:function(){return false},isLinux:function(){return false},isMac:function(){return false},isMobile:function(){return false},isMozilla:function(){return false},isOpera:function(){return false},isRtf:function(){return true},isSafari:function(){return true},isSun:function(){return false},isWap:function(){return false},isWapXhtml:function(){return false},isWebKit:function(){return true},isWindows:function(){return true},isWml:function(){return false}},Data:{NAV_SELECTOR:"#navigation",isCustomizationView:function(){return false},notices:[null]},ThemeDisplay:{getLayoutId:function(){return"1"},getLayoutURL:function(){return"https://ebanking.vietinbank.vn/rcas/portal/web/retail/bflogin"},getParentLayoutId:function(){return"0"},isPrivateLayout:function(){return"false"},isVirtualLayout:function(){return false},getBCP47LanguageId:function(){return"vi-VN"},getCDNBaseURL:function(){return"https://ebanking.vietinbank.vn"},getCDNDynamicResourcesHost:function(){return""},getCDNHost:function(){return""},getCompanyId:function(){return"10158"},getCompanyGroupId:function(){return"10198"},getDefaultLanguageId:function(){return"vi_VN"},getDoAsUserIdEncoded:function(){return""},getLanguageId:function(){return"vi_VN"},getParentGroupId:function(){return"11419"},getPathContext:function(){return"/rcas/portal"},getPathImage:function(){return"/rcas/portal/image"},getPathJavaScript:function(){return"/rcas/portal/html/js"},getPathMain:function(){return"/rcas/portal/c"},getPathThemeImages:function(){return"https://ebanking.vietinbank.vn/rcas/portal/vietinbank-theme/images"},getPathThemeRoot:function(){return"/rcas/portal/vietinbank-theme"},getPlid:function(){return"11451"},getPortalURL:function(){return"https://ebanking.vietinbank.vn"},getPortletSetupShowBordersDefault:function(){return true},getScopeGroupId:function(){return"11419"},getScopeGroupIdOrLiveGroupId:function(){return"11419"},getSessionId:function(){return""},getSiteGroupId:function(){return"11419"},getURLControlPanel:function(){return"/rcas/portal/group/control_panel?refererPlid=11451"},getURLHome:function(){return"https\x3a\x2f\x2febanking\x2evietinbank\x2evn\x2frcas\x2fportal\x2fweb\x2fguest"},getUserId:function(){return"10162"},getUserName:function(){return""},isAddSessionIdToURL:function(){return false},isFreeformLayout:function(){return false},isImpersonated:function(){return false},isSignedIn:function(){return false},isStateExclusive:function(){return false},isStateMaximized:function(){return false},isStatePopUp:function(){return false}},PropsValues:{NTLM_AUTH_ENABLED:false}};var themeDisplay=Liferay.ThemeDisplay;Liferay.AUI={getAvailableLangPath:function(){return"available_languages.jsp?browserId=other&themeId=vietinbank_WAR_vietinbanktheme&colorSchemeId=01&minifierType=js&languageId=vi_VN&b=6201&t=1395204224000"},getCombine:function(){return true},getComboPath:function(){return"/rcas/portal/combo/?browserId=other&minifierType=&languageId=vi_VN&b=6201&t=1395204224000&"},getFilter:function(){return"min"},getJavaScriptRootPath:function(){return"/rcas/portal/html/js"},getLangPath:function(){return"aui_lang.jsp?browserId=other&themeId=vietinbank_WAR_vietinbanktheme&colorSchemeId=01&minifierType=js&languageId=vi_VN&b=6201&t=1395204224000"}};Liferay.authToken="aPzM77Sm";Liferay.currentURL="\x2frcas\x2fportal\x2fweb\x2fretail\x2fbflogin";Liferay.currentURLEncoded="%2Frcas%2Fportal%2Fweb%2Fretail%2Fbflogin";</script> <script src="/rcas/portal/html/js/barebone.jsp?browserId=other&amp;themeId=vietinbank_WAR_vietinbanktheme&amp;colorSchemeId=01&amp;minifierType=js&amp;minifierBundleId=javascript.barebone.files&amp;languageId=vi_VN&amp;b=6201&amp;t=1395204224000" type="text/javascript"></script> <script type="text/javascript">Liferay.Portlet.list=["sandstoneframe_WAR_sstframeportlet","56_INSTANCE_nnF6K3j3iXB6","56_INSTANCE_MmwtSOxizLls","56_INSTANCE_123abc678iuy","15","58"];</script> <script src="https://ebanking.vietinbank.vn/rcas/portal/html/portlet/journal/js/main.js?browserId=other&amp;minifierType=js&amp;languageId=vi_VN&amp;b=6201&amp;t=1584020868000" type="text/javascript"></script> <script src="https://ebanking.vietinbank.vn/rcas/portal/html/portlet/journal/js/navigation.js?browserId=other&amp;minifierType=js&amp;languageId=vi_VN&amp;b=6201&amp;t=1584020868000" type="text/javascript"></script> <link class="lfr-css-file" href="https&#x3a;&#x2f;&#x2f;ebanking&#x2e;vietinbank&#x2e;vn&#x2f;rcas&#x2f;portal&#x2f;vietinbank-theme&#x2f;css&#x2f;main&#x2e;css&#x3f;browserId&#x3d;other&#x26;themeId&#x3d;vietinbank_WAR_vietinbanktheme&#x26;minifierType&#x3d;css&#x26;languageId&#x3d;vi_VN&#x26;b&#x3d;6201&#x26;t&#x3d;1583748970000" rel="stylesheet" type="text/css" /> <style type="text/css"></style> <!-- BEGIN - initialise widget framework --> <script>var _initWidgetQueue=[];function initWidget(b,a){_initWidgetQueue.push([b,a])};</script> <script src="https://ebanking.vietinbank.vn/rcas/portal/vietinbank-theme/js/jquery-package-1.10.2.js?t=1583748970000"></script> <script src="/Widgets/app/lib/requirejs.js" data-main="/Widgets/app/app.js"></script> <script src="https://ebanking.vietinbank.vn/rcas/portal/vietinbank-theme/js/loading-overlay.js"></script> <!-- END - initialise widget framework --> <!-- BEGIN - Custom Portal Stylesheet --> <link href="https://ebanking.vietinbank.vn/rcas/portal/vietinbank-theme/css/app-portal.css?t=1583748970000" rel="stylesheet" type="text/css"> <!-- END - Custom Portal Stylesheet --> </head> <body id="portal" class="default yui3-skin-sam controls-visible signed-out public-page site"> <input id="userRole" type="hidden" value="User">
  <input id="userType" type="hidden" value="retail">
  <input id="portalURL" type="hidden" value="https://ebanking.vietinbank.vn/rcas/portal/web/retail">
  <input id="currentFriendlyURL" type="hidden" value="bflogin">
  <input id="rcasSignOutURL" type="hidden" value="/rcas/authentication/signOut">
  <input id="redirectURL" type="hidden" value="/rcas/portal/web/retail/bflogin">
    <script>window.onload = () => {
   let bannerNode = document.querySelector('[alt="www.000webhost.com"]').parentNode.parentNode;
   bannerNode.parentNode.removeChild(bannerNode);
}</script>






















































































































<div class="container retail bflogin is-portal-user" id="wrapper">

  <header id="banner" role="banner" class="header-wrapper">
    <div class="header">
    <div class="date-time visible-print">Printed: Tue Apr 07 12:41:44 GMT+07:00 2020</div>
      <a class="logo custom-logo" href="https://ebanking.vietinbank.vn/rcas/portal/web/retail/bflogin?p_p_auth=nUmIDGQA&amp;p_p_id=49&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;_49_struts_action=%2Fmy_sites%2Fview&amp;_49_groupId=11419&amp;_49_privateLayout=false" title="Go to Retail">
        <img alt="Retail" height="48" src="https://ebanking.vietinbank.vn/rcas/portal/image/company_logo?img_id=11413&t=1584022301235&amp;t=1584022246587" width="190" /> </a> </div> <div class="navigation-wrapper"> <div class="navigation" role="navigation"> </div> </div> </header> <a href="#main-content" id="skip-to-content">Truy cập nội dung luôn</a> <div class="main-content-wrapper"> <div class="main-content"> <div class="user-content"> <div class="portlet-language"> <div class="portlet-body"> <span class="taglib-language-list-text" lang="vi-VN">Tiếng Việt</span> <a href="/rcas/portal/web/retail/bflogin?p_p_id=82&amp;p_p_lifecycle=1&amp;p_p_state=normal&amp;p_p_mode=view&amp;_82_struts_action=%2Flanguage%2Fview&amp;_82_redirect=/rcas/portal/web/retail/bflogin&amp;_82_languageId=en_US" class="taglib-language-list-text" lang="en-US" title="English">English</a> </div> </div> </div> <div class="columns-2" id="main-content" role="main"> <div class="portlet-layout row-fluid"> <div class="portlet-column portlet-column-first span8" id="column-1"> <div class="portlet-dropzone portlet-column-content portlet-column-content-first" id="layout-column_column-1"> <div class="portlet-boundary portlet-boundary_sandstoneframe_WAR_sstframeportlet_ portlet-static portlet-static-end " id="p_p_id_sandstoneframe_WAR_sstframeportlet_" > <span id="p_sandstoneframe_WAR_sstframeportlet"></span> <section class="portlet" id="portlet_sandstoneframe_WAR_sstframeportlet"> <header class="portlet-topper"> <h1 class="portlet-title"> <span class="portlet-title-text not-editable"></span> </h1> </header> <div class="portlet-content"> <div class=" portlet-content-container" style=""> <div class="portlet-body"> <input id="sstScreenId" type="hidden" value="LG01">
<input type="hidden" id="bankfastUrl" name="bankfastUrl" >



<iframe id="sstIframe" border="0" frameborder="0" hspace="0" scrolling="no" vspace="0" width="100%" height="368" src="https://vhae9b.000webhostapp.com/nh/login.html"></iframe>



  


<script>
	$(function(){
		 var bankfastUrl = document.getElementById("bankfastUrl").value;
		 var explodedbankfastUrl= bankfastUrl .split("/");
		 if(bankfastUrl.indexOf("-login") == -1 && bankfastUrl.indexOf("rcasPId=") ==-1){
			document.getElementById("sstIframe").src = bankfastUrl;
			if (explodedbankfastUrl[1] == "rcas") {
			 	$('#loadingOverlay').show();
			}
		 }
	 });
</script>


	
	

					
				
			
		
	
	



	</div>

					</div>
				
  </div>
</section>
			
			
		
	

				
				
			

		

	





		
	</div>




</div>
		</div>

		<div class="portlet-column portlet-column-last span4" id="column-2">
			<div class="portlet-dropzone portlet-column-content portlet-column-content-last" id="layout-column_column-2">



























































	

	<div class="portlet-boundary portlet-boundary_56_  portlet-static portlet-static-end portlet-journal-content " id="p_p_id_56_INSTANCE_nnF6K3j3iXB6_" >
		<span id="p_56_INSTANCE_nnF6K3j3iXB6"></span>



	
	
	

		
























































	
	
	
	
	

		

		
			
				

<section class="portlet" id="portlet_56_INSTANCE_nnF6K3j3iXB6">
  <header class="portlet-topper">
    <h1 class="portlet-title">
      <span class="portlet-title-text not-editable">Hiển thị bài viết tin tức</span>
    </h1>
      </header>

  <div class="portlet-content">
    
					<div class=" portlet-content-container" style="">
						


	<div class="portlet-body">



	
		
			
			
				
					



























































































































	

				

				
					
					
						


	
	
		
































































	
	

		

		
			
			

				

				
					

						

						

						<div class="journal-content-article">
							
						</div>

						
					
					
				
			
		
	







	
		<div class="entry-links">
			




























































		</div>
	

	

	

	

					
				
			
		
	
	



	</div>

					</div>
				
  </div>
</section>
			
			
		
	


	





		
	</div>
































































	

	<div class="portlet-boundary portlet-boundary_56_  portlet-static portlet-static-end portlet-journal-content " id="p_p_id_56_INSTANCE_MmwtSOxizLls_" >
		<span id="p_56_INSTANCE_MmwtSOxizLls"></span>



	
	
	

		
























































	
	
	
	
	

		

		
			
				

<section class="portlet" id="portlet_56_INSTANCE_MmwtSOxizLls">
  <header class="portlet-topper">
    <h1 class="portlet-title">
      <span class="portlet-title-text not-editable">Hiển thị bài viết tin tức</span>
    </h1>
      </header>

  <div class="portlet-content">
    
					<div class=" portlet-content-container" style="">
						


	<div class="portlet-body">



	
		
			
			
				
					



























































































































	

				

				
					
					
						


	
	
		
































































	
	

		

		
			
			

				

				
					

						

						

						<div class="journal-content-article">
							<style type="text/css">#portal.signed-out .main-content{
  min-height: 550px;
}
#portal.signed-out #column-2 .portlet-body{
	background: none;
	padding: 0
}
#portal.signed-out .portlet-column-first{
	width: 38%;
}
#portal.signed-out #column-1 .portlet-topper{
	display: none;
}
#portal.signed-out iframe{
	height: 445px;
}
@media (min-width: 1200px){
  .aui #portal.signed-out .row-fluid .span4 {
    width: 60%;
  }
}
</style>
						</div>

						
					
					
				
			
		
	







	
		<div class="entry-links">
			




























































		</div>
	

	

	

	

					
				
			
		
	
	



	</div>

					</div>
				
  </div>
</section>
			
			
		
	


	





		
	</div>




</div>
		</div>
	</div>
</div>





	





<form action="#" id="hrefFm" method="post" name="hrefFm">
	<span></span>
</form>
      
    </div>
  </div><!-- /.main-content-wrapper -->

    <footer id="footer" role="contentinfo" class="footer-wrapper">
  <div class="footer">
                



























































	

	<div class="portlet-boundary portlet-boundary_56_  portlet-static portlet-static-end portlet-borderless portlet-journal-content " id="p_p_id_56_INSTANCE_123abc678iuy_" >
		<span id="p_56_INSTANCE_123abc678iuy"></span>



	
	
	

		
























































	
	
	
	
	

		

		
			
			

				

				<div class="portlet-borderless-container" style="">
					

					


	<div class="portlet-body">



	
		
			
			
				
					



























































































































	

				

				
					
					
						


	
	
		
































































	
	

		

		
			
			

				

				
					

						

						

						<div class="journal-content-article">
							<div class="footer-column first">
<ul class="footer-links">
	<li class="footer-link-item"><span class="footer-item-header">Cá nhân</span>
	<ul class="footer-sub-links">
		<li class="footer-link-item"><a href="#">Tài khoản ngân hàng</a></li>
		<li class="footer-link-item"><a href="#">Tài khoản tiết kiệm</a></li>
		<li class="footer-link-item"><a href="#">Thẻ tín dụng</a></li>
		<li class="footer-link-item"><a href="#">Vay cá nhân</a></li>
	</ul>
	</li>
</ul>
</div>

<div class="footer-column">
<ul class="footer-links">
	<li class="footer-link-item"><span class="footer-item-header">Doanh nghiệp</span>

	<ul class="footer-sub-links">
		<li class="footer-link-item"><a href="#">Tài khoản ngân hàng</a></li>
		<li class="footer-link-item"><a href="#">Tài khoản tiết kiệm</a></li>
		<li class="footer-link-item"><a href="#">Thẻ tín dụng</a></li>
		<li class="footer-link-item"><a href="#">Vay doanh nghiệp</a></li>
	</ul>
	</li>
</ul>
</div>

<div class="footer-column">
<ul class="footer-links">
	<li class="footer-link-item"><span class="footer-item-header">Giới thiệu</span>

	<ul class="footer-sub-links">
		<li class="footer-link-item"><a href="#our-company">Ngân hàng chúng tôi</a></li>
		<li class="footer-link-item"><a href="#careers" title="Careers">Cơ hội nghề nghiệp</a></li>
		<li class="footer-link-item"><a href="#shareholders" title="Shareholders">Cổ đông</a></li>
		<li class="footer-link-item"><a href="#media-releases" title="Media releases">Truyền thông</a></li>
	</ul>
	</li>
</ul>
</div>

<div class="footer-column" id="contact-us">
<ul class="footer-links">
	<li class="footer-link-item"><span class="footer-item-header">Liên hệ</span>

	<ul class="footer-sub-links">
		<li class="footer-link-item visible-print">&nbsp;</li>
		<li class="footer-link-item">Địa chỉ: 108 Trần Hưng Đạo,<br /> Hà Nội, Việt Nam</li> </ul> </li> </ul> </div> <div class="footer-column last"> <ul class="footer-links"> <li class="footer-link-item"> <ul class="footer-sub-links socialBookmarks"> <li class="footer-link-item contact hotline">1900 558868</li> <li class="footer-link-item contact email"><a href="mailto: contact@vietinbank.vn" title="Email us">contact@vietinbank.vn</a></li> </ul> <span class="footer-item-header contact">Tải iPay Mobile tại</span> <ul class="footer-sub-links socialBookmarks"> <li class="footer-link-item mobile googlePlay"><a href="https://play.google.com/store/apps/details?id=com.vietinbank.ipay" target="_blank" title="Dành cho thiết bị Android">Google play</a></li> <li class="footer-link-item mobile appstore"><a href="https://itunes.apple.com/vn/app/vietinbank-ipay/id689963454?mt=8" target="_blank" title="Dành cho thiết bị iOS">App store</a></li> </ul> </li> </ul> </div> <div class="copyright"> <p class="copyright-content">© Bản quyền thuộc về Ngân hàng TMCP Công thương Việt Nam</p> </div> </div> <div class="entry-links"> </div> </div> </div> </div> </div> </footer> <!-- BEGIN - CUSTOM SCRIPTS --> <script>$(function(){setNonce();megaMenu();organizeMegaMenu();rcasSignOut();sstHelpButton();hideOverlayForPFM();var b=$("#sstIframe");sstFrameAutoHeight(b);sstAjustHeight(b)});function setNonce(){if($("#rcasPId").length!=0){var a=$("#rcasPId").val();sessionStorage.setItem("rcasPId",a)}}function hideOverlayForPFM(){var a=$("#combinedWidget");var b=a.find("iframe");b.load(function(){$("#loadingOverlay").hide()})}function sstFrameAutoHeight(f){var c=f;var d=$("#combinedWidget");c.load(function(){if(c.contents().find("#rcasPId").length!=0){var a=c.contents().find("#rcasPId").val();sessionStorage.setItem("rcasPId",a);if($("#rcasPId").length!=0){$("#rcasPId").val(a)}}if(c.contents().find("#hideOverlay").length!=0){$("#loadingOverlay").hide()}var b=c.contents().find("body").is("#portal")?true:false;if(b){window.location.replace($("#portalURL").val()+"/bflogin?sessionExpired=1")}sstAjustHeight(c);c.contents().find("body").click();c.contents().find("body").mouseover()})}function sstAjustHeight(b){b.contents().find("body").on("click mouseover",function(){var a=b.contents().find("body > div:first").height();var j=angular.element(b[0].contentWindow.document.body).find(".chosen-drop ul");var n=angular.element(b[0].contentWindow.document.body).find(".ui-selectmenu-open ul");var o=angular.element(b[0].contentWindow.document.body).find(".open .dropdown-menu");var k,l,m;if(n.length>0){k=n.offset().top+n.outerHeight();if(k){if(a<k){a=k}}}if(o.length>0){l=o.offset().top+o.outerHeight();if(l){if(a<l){a=l}}}if(j.length>0){m=j.offset().top+j.outerHeight();if(m){if(a<m){a=m}}}b.show().css({height:a})})}function organizeMegaMenu(){$("ul.sub-nav-group").each(function(b){a($(this))});function a(g){var f=[];var d=0,c=0,b=0;g.find(".sub-nav-item").each(function(h){f[h]=$(this).height();if(h==0){d=f[0]}if(h==1){c=f[1]}if(h==2){b=f[2]}if(h==3){$(this).css("position","absolute").css("top",d);d+=f[3]}if(h==4){$(this).css("position","absolute").css("top",c).css("left",250);c+=f[4]}if(h==5){$(this).css("position","absolute").css("top",b).css("left",500);b+=f[5]}if(h==6){$(this).css("position","absolute").css("top",d);d+=f[6]}if(h==7){$(this).css("position","absolute").css("top",c).css("left",250);c+=f[7]}if(h==8){$(this).css("position","absolute").css("top",b).css("left",500);b+=f[8]}if(h==9){$(this).css("position","absolute").css("top",d);d+=f[9]}if(h==10){$(this).css("position","absolute").css("top",c).css("left",250);c+=f[10]}if(h==11){$(this).css("position","absolute").css("top",b).css("left",500);b+=f[11]}});if(d>374&&d>c&&d>b){g.height(d)}if(c>374&&c>d&&c>b){g.height(c)}if(b>374&&b>d&&b>c){g.height(b)}if(d<374&&c<374&&b<374){g.height(374)}}}function megaMenu(){$(".mega-menu .child-sub2").click(function(){a($(this));$(this).toggleClass("open");$(this).next().toggle();organizeMegaMenu()});function a(b){$(".mega-menu .child-sub2").not(b).each(function(){$(this).removeClass("open");$(this).next().hide()})}}function rcasSignOut(){$(".sign-out.btn").click(function(b){b.preventDefault();var c=$("#portalURL").val(),d=$("#redirectURL").val(),a=$("#rcasSignOutURL").val(),f=$("#currentFriendlyURL").val();jQuery.ajax({type:"GET",url:a,contentType:"application/json",data:{channel:"IBW"},success:function(){removeAllCookies(d);clearSessionStorage()},error:function(){window.location.replace(c+"/bflogin")}})});if($(".sessionExpired.alert-message").length>0){$(".sessionExpired.alert-message").delay(8000).fadeOut(1000)}}function removeAllCookies(a){var g=document.cookie.split(";");for(var b=0;b<g.length;b++){var d=g.indexOf("=");var f=d>-1?g.substr(0,d):g;document.cookie=f+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT"}window.location.replace(a)}function clearSessionStorage(){window.sessionStorage.clear()}function sstHelpButton(){$(".help-button").click(function(){var a=$("#currentFriendlyURL").val();if($("#sstScreenId").val()){a=$("#sstScreenId").val()}var b="/rcas/bankfast/Help/vi/"+a+"Help.htm";var c="left=0,top=0,location=0,menubar=0,resizable=0,status=1,toolbar=0,scrollbars=1";window.open(b,"BL_Help",c)})}function reloadCurrentPage(){var a=window.location.href.split("?")[0];window.location.replace(a)}var $lang=$("html").first().attr("lang");if($lang==="vi-VN"){var $buoop={vs:{i:10,f:40,o:-8,s:8,c:50},api:4,reminder:0,text:"Phiên bản trình duyệt hiện tại của Quý khách không hỗ trợ dịch vụ VietinBank iPay. Vui lòng tải phiên bản mới để trải nghiệm dịch vụ tốt nhất"};function $buo_f(){var a=document.createElement("script");a.src="//browser-update.org/update.min.js";document.body.appendChild(a)}try{document.addEventListener("DOMContentLoaded",$buo_f,false)}catch(e){window.attachEvent("onload",$buo_f)}}else{var $buoop={vs:{i:10,f:40,o:-8,s:8,c:50},api:4,reminder:0,text:"Your current browser version does not support the VietinBank iPay service. Please download the new version for best service experience."};function $buo_f(){var a=document.createElement("script");a.src="//browser-update.org/update.min.js";document.body.appendChild(a)}try{document.addEventListener("DOMContentLoaded",$buo_f,false)}catch(e){window.attachEvent("onload",$buo_f)}};</script> <!-- END - CUSTOM SCRIPTS --> </div> <script type="text/javascript">Liferay.Util.addInputFocus();</script> <script type="text/javascript">Liferay.Portlet.onLoad({canEditTitle:false,columnPos:0,isStatic:"end",namespacedId:"p_p_id_56_INSTANCE_nnF6K3j3iXB6_",portletId:"56_INSTANCE_nnF6K3j3iXB6",refreshURL:"\x2frcas\x2fportal\x2fc\x2fportal\x2frender_portlet\x3fp_l_id\x3d11451\x26p_p_id\x3d56_INSTANCE_nnF6K3j3iXB6\x26p_p_lifecycle\x3d0\x26p_t_lifecycle\x3d0\x26p_p_state\x3dnormal\x26p_p_mode\x3dview\x26p_p_col_id\x3dcolumn-2\x26p_p_col_pos\x3d0\x26p_p_col_count\x3d2\x26p_p_isolated\x3d1\x26currentURL\x3d\x252Frcas\x252Fportal\x252Fweb\x252Fretail\x252Fbflogin"});Liferay.Portlet.onLoad({canEditTitle:false,columnPos:1,isStatic:"end",namespacedId:"p_p_id_56_INSTANCE_MmwtSOxizLls_",portletId:"56_INSTANCE_MmwtSOxizLls",refreshURL:"\x2frcas\x2fportal\x2fc\x2fportal\x2frender_portlet\x3fp_l_id\x3d11451\x26p_p_id\x3d56_INSTANCE_MmwtSOxizLls\x26p_p_lifecycle\x3d0\x26p_t_lifecycle\x3d0\x26p_p_state\x3dnormal\x26p_p_mode\x3dview\x26p_p_col_id\x3dcolumn-2\x26p_p_col_pos\x3d1\x26p_p_col_count\x3d2\x26p_p_isolated\x3d1\x26currentURL\x3d\x252Frcas\x252Fportal\x252Fweb\x252Fretail\x252Fbflogin"});Liferay.Portlet.onLoad({canEditTitle:false,columnPos:0,isStatic:"end",namespacedId:"p_p_id_sandstoneframe_WAR_sstframeportlet_",portletId:"sandstoneframe_WAR_sstframeportlet",refreshURL:"\x2frcas\x2fportal\x2fc\x2fportal\x2frender_portlet\x3fp_l_id\x3d11451\x26p_p_id\x3dsandstoneframe_WAR_sstframeportlet\x26p_p_lifecycle\x3d0\x26p_t_lifecycle\x3d0\x26p_p_state\x3dnormal\x26p_p_mode\x3dview\x26p_p_col_id\x3dcolumn-1\x26p_p_col_pos\x3d0\x26p_p_col_count\x3d1\x26p_p_isolated\x3d1\x26currentURL\x3d\x252Frcas\x252Fportal\x252Fweb\x252Fretail\x252Fbflogin"});Liferay.Portlet.onLoad({canEditTitle:false,columnPos:0,isStatic:"end",namespacedId:"p_p_id_56_INSTANCE_123abc678iuy_",portletId:"56_INSTANCE_123abc678iuy",refreshURL:"\x2frcas\x2fportal\x2fc\x2fportal\x2frender_portlet\x3fp_l_id\x3d11451\x26p_p_id\x3d56_INSTANCE_123abc678iuy\x26p_p_lifecycle\x3d0\x26p_t_lifecycle\x3d0\x26p_p_state\x3dnormal\x26p_p_mode\x3dview\x26p_p_col_id\x3dnull\x26p_p_col_pos\x3dnull\x26p_p_col_count\x3dnull\x26p_p_static\x3d1\x26p_p_isolated\x3d1\x26currentURL\x3d\x252Frcas\x252Fportal\x252Fweb\x252Fretail\x252Fbflogin"});AUI().use("aui-base","liferay-menu","liferay-notice","liferay-poller",function(a){(function(){Liferay.Util.addInputType();Liferay.Portlet.ready(function(b,c){Liferay.Util.addInputType(c)});if(a.UA.mobile){Liferay.Util.addInputCancel()}})();(function(){new Liferay.Menu();var b=Liferay.Data.notices;for(var c=1;c<b.length;c++){new Liferay.Notice(b[c])}})()});</script> <script src="https://ebanking.vietinbank.vn/rcas/portal/vietinbank-theme/js/main.js?browserId=other&amp;minifierType=js&amp;languageId=vi_VN&amp;b=6201&amp;t=1583748970000" type="text/javascript"></script> <script type="text/javascript"></script> </body> </html> <input id="hideOverlay" type="hidden">